//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerManagement.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class table_Registration
    {
        
        public int id { get; set; }
        [Required(ErrorMessage ="Name Is Required")]
        public string name { get; set; }
        [Required(ErrorMessage = "Password Is Required")]
        [MinLength(6)]
        public string password { get; set; }
        [Required(ErrorMessage = "Email Is Required")]
        public string email { get; set; }
        [Required(ErrorMessage = "Address Is Required")]
        public string address { get; set; }
    }
}
